use_compute_credits: true

docker_builder:
  name: Test (Linux with Docker)
  alias: Tests
  test_script:
    - wget --no-verbose -O - https://go.dev/dl/go1.25.4.linux-amd64.tar.gz | tar -C /usr/local -xz
    - export PATH=$PATH:/usr/local/go/bin
    - go test ./...
  env:
    HOME: /root

macos_task:
  name: Test (macOS without Docker)
  alias: Tests
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:tahoe
  install_script: brew install go
  test_script: go test ./...

task:
  name: Release (Dry Run)
  only_if: $CIRRUS_TAG == ''
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sequoia
  env:
    MACOS_SIGN_P12: ENCRYPTED[!183482723ca1a95f9c4439f7a79c9d3b115472bb18c739ed1586e12d3914ccf94ade8169eeda7332fc204f8be9c27d9f!]
    MACOS_SIGN_PASSWORD: ENCRYPTED[!417423346c567f12007f42d084bff1cfee30ee14f7e8258550157679a269c70d541c9f19224224ab0293b10f2c6d4c5e!]
    MACOS_NOTARY_ISSUER_ID: ENCRYPTED[!74076906e9fa36bca3c1da1637b0759b58bb009eb1a707446896eefad3767e8dba1d0f87e71106b98cde98ac4b037a2a!]
    MACOS_NOTARY_KEY_ID: ENCRYPTED[!af9e5da1010a6b04e548ef494acc77a6e0ce176549de98f81c5b5cdd72856de09f77e51cf0849e3c4b7a2d2c22f25ca8!]
    MACOS_NOTARY_KEY: ENCRYPTED[!c70c53f3e6c163931c7cdf9d90aff8934ef21d5dd1090158688e00b94e97c68257d9cf4ae1df873e6ae0d949866aee72!]
    GORELEASER_KEY: ENCRYPTED[!9b80b6ef684ceaf40edd4c7af93014ee156c8aba7e6e5795f41c482729887b5c31f36b651491d790f1f668670888d9fd!]
  install_script:
    - brew update && brew install go
    - brew install --cask goreleaser/tap/goreleaser-pro
  goreleaser_script: goreleaser release --skip=publish --snapshot --clean --verbose
  binaries_artifacts:
    path: "dist/omni-cache_*/omni-cache*"

task:
  name: Release
  only_if: $CIRRUS_TAG != ''
  depends_on: Tests
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sequoia
  env:
    MACOS_SIGN_P12: ENCRYPTED[!183482723ca1a95f9c4439f7a79c9d3b115472bb18c739ed1586e12d3914ccf94ade8169eeda7332fc204f8be9c27d9f!]
    MACOS_SIGN_PASSWORD: ENCRYPTED[!417423346c567f12007f42d084bff1cfee30ee14f7e8258550157679a269c70d541c9f19224224ab0293b10f2c6d4c5e!]
    MACOS_NOTARY_ISSUER_ID: ENCRYPTED[!74076906e9fa36bca3c1da1637b0759b58bb009eb1a707446896eefad3767e8dba1d0f87e71106b98cde98ac4b037a2a!]
    MACOS_NOTARY_KEY_ID: ENCRYPTED[!af9e5da1010a6b04e548ef494acc77a6e0ce176549de98f81c5b5cdd72856de09f77e51cf0849e3c4b7a2d2c22f25ca8!]
    MACOS_NOTARY_KEY: ENCRYPTED[!c70c53f3e6c163931c7cdf9d90aff8934ef21d5dd1090158688e00b94e97c68257d9cf4ae1df873e6ae0d949866aee72!]
    GITHUB_TOKEN: ENCRYPTED[!98ace8259c6024da912c14d5a3c5c6aac186890a8d4819fad78f3e0c41a4e0cd3a2537dd6e91493952fb056fa434be7c!]
    FURY_TOKEN: ENCRYPTED[!97fe4497d9aca60a3d64904883b81e21f19706c6aedda625c97f62f67ec46b8efa74c55699956158bbf0a23726e7d9f6!]
    GORELEASER_KEY: ENCRYPTED[!9b80b6ef684ceaf40edd4c7af93014ee156c8aba7e6e5795f41c482729887b5c31f36b651491d790f1f668670888d9fd!]
  install_script:
    - brew update && brew install go
    - brew install --cask goreleaser/tap/goreleaser-pro
  release_script: goreleaser

task:
  name: Check for lacking "buf generate" invocation

  container:
    image: golang:latest

  install_buf_script: go install github.com/bufbuild/buf/cmd/buf@v1.50.0
  install_protoc_gen_twirp_script: go install github.com/twitchtv/twirp/protoc-gen-twirp@latest
  generate_script: buf generate
  check_script: git diff --exit-code

task:
  name: Check for lacking "go generate ./..." invocation

  container:
    image: golang:latest

  generate_script: go generate ./...
  check_script: git diff --exit-code
