version: 2

project_name: omni-cache

before:
  hooks:
    - go mod download

builds:
  - main: cmd/omni-cache/main.go
    ldflags: >
      -X github.com/cirruslabs/omni-cache/internal/version.Version={{.Version}}
      -X github.com/cirruslabs/omni-cache/internal/version.Commit={{.ShortCommit}}
    env:
      - CGO_ENABLED={{if eq .Os "darwin"}}1{{else}}0{{end}}
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - netbsd
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
    ignore:
      - goos: windows
        goarch: arm
    hooks:
      post:
        - bash .ci/remove-signature.sh {{ .Path }}

archives:
  - id: binary
    formats: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  - id: regular
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  prerelease: auto

brews:
  - name: omni-cache
    ids:
      - regular
    repository:
      owner: cirruslabs
      name: homebrew-cli
    license: FSL-1.1-ALv2
    install: |
      bin.install "omni-cache"
    caveats: See the Github repository for more information

nfpms:
  - package_name: omni-cache
    vendor: Cirrus Labs, Inc.
    homepage: https://github.com/cirruslabs/omni-cache
    maintainer: support@cirruslabs.org
    description: Omni Cache sidecar for CI caching workloads
    license: FSL-1.1-ALv2
    section: devel
    formats:
      - deb
      - rpm

furies:
  - account: cirruslabs

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
