// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CleanProjectCacheOperation                  OperationName = "CleanProjectCache"
	CompleteModuleCacheMultipartUploadOperation OperationName = "CompleteModuleCacheMultipartUpload"
	DownloadCASArtifactOperation                OperationName = "DownloadCASArtifact"
	DownloadModuleCacheArtifactOperation        OperationName = "DownloadModuleCacheArtifact"
	GetKeyValueOperation                        OperationName = "GetKeyValue"
	ModuleCacheArtifactExistsOperation          OperationName = "ModuleCacheArtifactExists"
	PutKeyValueOperation                        OperationName = "PutKeyValue"
	SaveCASArtifactOperation                    OperationName = "SaveCASArtifact"
	StartModuleCacheMultipartUploadOperation    OperationName = "StartModuleCacheMultipartUpload"
	UploadModuleCachePartOperation              OperationName = "UploadModuleCachePart"
)
