// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"io"
)

type CleanProjectCacheForbidden Error

func (*CleanProjectCacheForbidden) cleanProjectCacheRes() {}

type CleanProjectCacheInternalServerError Error

func (*CleanProjectCacheInternalServerError) cleanProjectCacheRes() {}

// CleanProjectCacheNoContent is response for CleanProjectCache operation.
type CleanProjectCacheNoContent struct{}

func (*CleanProjectCacheNoContent) cleanProjectCacheRes() {}

type CleanProjectCacheUnauthorized Error

func (*CleanProjectCacheUnauthorized) cleanProjectCacheRes() {}

type CompleteModuleCacheMultipartUploadBadRequest Error

func (*CompleteModuleCacheMultipartUploadBadRequest) completeModuleCacheMultipartUploadRes() {}

type CompleteModuleCacheMultipartUploadForbidden Error

func (*CompleteModuleCacheMultipartUploadForbidden) completeModuleCacheMultipartUploadRes() {}

type CompleteModuleCacheMultipartUploadInternalServerError Error

func (*CompleteModuleCacheMultipartUploadInternalServerError) completeModuleCacheMultipartUploadRes() {
}

// CompleteModuleCacheMultipartUploadNoContent is response for CompleteModuleCacheMultipartUpload operation.
type CompleteModuleCacheMultipartUploadNoContent struct{}

func (*CompleteModuleCacheMultipartUploadNoContent) completeModuleCacheMultipartUploadRes() {}

type CompleteModuleCacheMultipartUploadNotFound Error

func (*CompleteModuleCacheMultipartUploadNotFound) completeModuleCacheMultipartUploadRes() {}

type CompleteModuleCacheMultipartUploadUnauthorized Error

func (*CompleteModuleCacheMultipartUploadUnauthorized) completeModuleCacheMultipartUploadRes() {}

// Request to complete a multipart upload.
// Ref: #/components/schemas/CompleteMultipartUploadRequest
type CompleteMultipartUploadRequest struct {
	// Ordered list of part numbers that were uploaded.
	Parts []int `json:"parts"`
}

// GetParts returns the value of Parts.
func (s *CompleteMultipartUploadRequest) GetParts() []int {
	return s.Parts
}

// SetParts sets the value of Parts.
func (s *CompleteMultipartUploadRequest) SetParts(val []int) {
	s.Parts = val
}

type DownloadCASArtifactBadRequest Error

func (*DownloadCASArtifactBadRequest) downloadCASArtifactRes() {}

type DownloadCASArtifactForbidden Error

func (*DownloadCASArtifactForbidden) downloadCASArtifactRes() {}

type DownloadCASArtifactNotFound Error

func (*DownloadCASArtifactNotFound) downloadCASArtifactRes() {}

type DownloadCASArtifactOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s DownloadCASArtifactOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*DownloadCASArtifactOK) downloadCASArtifactRes() {}

type DownloadCASArtifactUnauthorized Error

func (*DownloadCASArtifactUnauthorized) downloadCASArtifactRes() {}

type DownloadModuleCacheArtifactBadRequest Error

func (*DownloadModuleCacheArtifactBadRequest) downloadModuleCacheArtifactRes() {}

type DownloadModuleCacheArtifactForbidden Error

func (*DownloadModuleCacheArtifactForbidden) downloadModuleCacheArtifactRes() {}

type DownloadModuleCacheArtifactNotFound Error

func (*DownloadModuleCacheArtifactNotFound) downloadModuleCacheArtifactRes() {}

type DownloadModuleCacheArtifactOK struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s DownloadModuleCacheArtifactOK) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*DownloadModuleCacheArtifactOK) downloadModuleCacheArtifactRes() {}

type DownloadModuleCacheArtifactUnauthorized Error

func (*DownloadModuleCacheArtifactUnauthorized) downloadModuleCacheArtifactRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	// The error message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

type GetKeyValueBadRequest Error

func (*GetKeyValueBadRequest) getKeyValueRes() {}

type GetKeyValueNotFound Error

func (*GetKeyValueNotFound) getKeyValueRes() {}

type GetKeyValueUnauthorized Error

func (*GetKeyValueUnauthorized) getKeyValueRes() {}

// Ref: #/components/schemas/KeyValueResponse
type KeyValueResponse struct {
	// The list of key-value entries.
	Entries []KeyValueResponseEntriesItem `json:"entries"`
}

// GetEntries returns the value of Entries.
func (s *KeyValueResponse) GetEntries() []KeyValueResponseEntriesItem {
	return s.Entries
}

// SetEntries sets the value of Entries.
func (s *KeyValueResponse) SetEntries(val []KeyValueResponseEntriesItem) {
	s.Entries = val
}

func (*KeyValueResponse) getKeyValueRes() {}

type KeyValueResponseEntriesItem struct {
	// The value.
	Value string `json:"value"`
}

// GetValue returns the value of Value.
func (s *KeyValueResponseEntriesItem) GetValue() string {
	return s.Value
}

// SetValue sets the value of Value.
func (s *KeyValueResponseEntriesItem) SetValue(val string) {
	s.Value = val
}

type ModuleCacheArtifactExistsBadRequest Error

func (*ModuleCacheArtifactExistsBadRequest) moduleCacheArtifactExistsRes() {}

type ModuleCacheArtifactExistsForbidden Error

func (*ModuleCacheArtifactExistsForbidden) moduleCacheArtifactExistsRes() {}

// ModuleCacheArtifactExistsNoContent is response for ModuleCacheArtifactExists operation.
type ModuleCacheArtifactExistsNoContent struct{}

func (*ModuleCacheArtifactExistsNoContent) moduleCacheArtifactExistsRes() {}

type ModuleCacheArtifactExistsNotFound Error

func (*ModuleCacheArtifactExistsNotFound) moduleCacheArtifactExistsRes() {}

type ModuleCacheArtifactExistsUnauthorized Error

func (*ModuleCacheArtifactExistsUnauthorized) moduleCacheArtifactExistsRes() {}

// NewNilString returns new NilString with value set to v.
func NewNilString(v string) NilString {
	return NilString{
		Value: v,
	}
}

// NilString is nullable string.
type NilString struct {
	Value string
	Null  bool
}

// SetTo sets value to v.
func (o *NilString) SetTo(v string) {
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o NilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *NilString) SetToNull() {
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o NilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o NilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PutKeyValueBadRequest Error

func (*PutKeyValueBadRequest) putKeyValueRes() {}

// PutKeyValueNoContent is response for PutKeyValue operation.
type PutKeyValueNoContent struct{}

func (*PutKeyValueNoContent) putKeyValueRes() {}

type PutKeyValueReq struct {
	// The CAS ID.
	CasID   string                      `json:"cas_id"`
	Entries []PutKeyValueReqEntriesItem `json:"entries"`
}

// GetCasID returns the value of CasID.
func (s *PutKeyValueReq) GetCasID() string {
	return s.CasID
}

// GetEntries returns the value of Entries.
func (s *PutKeyValueReq) GetEntries() []PutKeyValueReqEntriesItem {
	return s.Entries
}

// SetCasID sets the value of CasID.
func (s *PutKeyValueReq) SetCasID(val string) {
	s.CasID = val
}

// SetEntries sets the value of Entries.
func (s *PutKeyValueReq) SetEntries(val []PutKeyValueReqEntriesItem) {
	s.Entries = val
}

type PutKeyValueReqEntriesItem struct {
	// The value.
	Value OptString `json:"value"`
}

// GetValue returns the value of Value.
func (s *PutKeyValueReqEntriesItem) GetValue() OptString {
	return s.Value
}

// SetValue sets the value of Value.
func (s *PutKeyValueReqEntriesItem) SetValue(val OptString) {
	s.Value = val
}

type PutKeyValueUnauthorized Error

func (*PutKeyValueUnauthorized) putKeyValueRes() {}

type SaveCASArtifactBadRequest Error

func (*SaveCASArtifactBadRequest) saveCASArtifactRes() {}

type SaveCASArtifactForbidden Error

func (*SaveCASArtifactForbidden) saveCASArtifactRes() {}

type SaveCASArtifactInternalServerError Error

func (*SaveCASArtifactInternalServerError) saveCASArtifactRes() {}

// SaveCASArtifactNoContent is response for SaveCASArtifact operation.
type SaveCASArtifactNoContent struct{}

func (*SaveCASArtifactNoContent) saveCASArtifactRes() {}

type SaveCASArtifactReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s SaveCASArtifactReq) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

type SaveCASArtifactRequestEntityTooLarge Error

func (*SaveCASArtifactRequestEntityTooLarge) saveCASArtifactRes() {}

type SaveCASArtifactRequestTimeout Error

func (*SaveCASArtifactRequestTimeout) saveCASArtifactRes() {}

type SaveCASArtifactUnauthorized Error

func (*SaveCASArtifactUnauthorized) saveCASArtifactRes() {}

type StartModuleCacheMultipartUploadBadRequest Error

func (*StartModuleCacheMultipartUploadBadRequest) startModuleCacheMultipartUploadRes() {}

type StartModuleCacheMultipartUploadForbidden Error

func (*StartModuleCacheMultipartUploadForbidden) startModuleCacheMultipartUploadRes() {}

type StartModuleCacheMultipartUploadUnauthorized Error

func (*StartModuleCacheMultipartUploadUnauthorized) startModuleCacheMultipartUploadRes() {}

// Response from starting a multipart upload.
// Ref: #/components/schemas/StartMultipartUploadResponse
type StartMultipartUploadResponse struct {
	// The upload ID to use for subsequent part uploads. Null if artifact already exists.
	UploadID NilString `json:"upload_id"`
}

// GetUploadID returns the value of UploadID.
func (s *StartMultipartUploadResponse) GetUploadID() NilString {
	return s.UploadID
}

// SetUploadID sets the value of UploadID.
func (s *StartMultipartUploadResponse) SetUploadID(val NilString) {
	s.UploadID = val
}

func (*StartMultipartUploadResponse) startModuleCacheMultipartUploadRes() {}

type UploadModuleCachePartBadRequest Error

func (*UploadModuleCachePartBadRequest) uploadModuleCachePartRes() {}

type UploadModuleCachePartForbidden Error

func (*UploadModuleCachePartForbidden) uploadModuleCachePartRes() {}

// UploadModuleCachePartNoContent is response for UploadModuleCachePart operation.
type UploadModuleCachePartNoContent struct{}

func (*UploadModuleCachePartNoContent) uploadModuleCachePartRes() {}

type UploadModuleCachePartNotFound Error

func (*UploadModuleCachePartNotFound) uploadModuleCachePartRes() {}

type UploadModuleCachePartReq struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s UploadModuleCachePartReq) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

type UploadModuleCachePartRequestEntityTooLarge Error

func (*UploadModuleCachePartRequestEntityTooLarge) uploadModuleCachePartRes() {}

type UploadModuleCachePartRequestTimeout Error

func (*UploadModuleCachePartRequestTimeout) uploadModuleCachePartRes() {}

type UploadModuleCachePartUnauthorized Error

func (*UploadModuleCachePartUnauthorized) uploadModuleCachePartRes() {}

type UploadModuleCachePartUnprocessableEntity Error

func (*UploadModuleCachePartUnprocessableEntity) uploadModuleCachePartRes() {}
