// Code generated by ogen, DO NOT EDIT.
package openapi

type CleanProjectCacheRes interface {
	cleanProjectCacheRes()
}

type CompleteModuleCacheMultipartUploadRes interface {
	completeModuleCacheMultipartUploadRes()
}

type DownloadCASArtifactRes interface {
	downloadCASArtifactRes()
}

type DownloadModuleCacheArtifactRes interface {
	downloadModuleCacheArtifactRes()
}

type GetKeyValueRes interface {
	getKeyValueRes()
}

type ModuleCacheArtifactExistsRes interface {
	moduleCacheArtifactExistsRes()
}

type PutKeyValueRes interface {
	putKeyValueRes()
}

type SaveCASArtifactRes interface {
	saveCASArtifactRes()
}

type StartModuleCacheMultipartUploadRes interface {
	startModuleCacheMultipartUploadRes()
}

type UploadModuleCachePartRes interface {
	uploadModuleCachePartRes()
}
