// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CleanProjectCache implements cleanProjectCache operation.
//
// Clean all cache artifacts for a project.
//
// DELETE /api/cache/clean
func (UnimplementedHandler) CleanProjectCache(ctx context.Context, params CleanProjectCacheParams) (r CleanProjectCacheRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CompleteModuleCacheMultipartUpload implements completeModuleCacheMultipartUpload operation.
//
// Complete a multipart module cache upload.
//
// POST /api/cache/module/complete
func (UnimplementedHandler) CompleteModuleCacheMultipartUpload(ctx context.Context, req *CompleteMultipartUploadRequest, params CompleteModuleCacheMultipartUploadParams) (r CompleteModuleCacheMultipartUploadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DownloadCASArtifact implements downloadCASArtifact operation.
//
// Download a CAS artifact.
//
// GET /api/cache/cas/{id}
func (UnimplementedHandler) DownloadCASArtifact(ctx context.Context, params DownloadCASArtifactParams) (r DownloadCASArtifactRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DownloadModuleCacheArtifact implements downloadModuleCacheArtifact operation.
//
// Download a module cache artifact.
//
// GET /api/cache/module/{id}
func (UnimplementedHandler) DownloadModuleCacheArtifact(ctx context.Context, params DownloadModuleCacheArtifactParams) (r DownloadModuleCacheArtifactRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetKeyValue implements getKeyValue operation.
//
// Get a key-value entry.
//
// GET /api/cache/keyvalue/{cas_id}
func (UnimplementedHandler) GetKeyValue(ctx context.Context, params GetKeyValueParams) (r GetKeyValueRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ModuleCacheArtifactExists implements moduleCacheArtifactExists operation.
//
// Check if a module cache artifact exists.
//
// HEAD /api/cache/module/{id}
func (UnimplementedHandler) ModuleCacheArtifactExists(ctx context.Context, params ModuleCacheArtifactExistsParams) (r ModuleCacheArtifactExistsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PutKeyValue implements putKeyValue operation.
//
// Put a key-value entry.
//
// PUT /api/cache/keyvalue
func (UnimplementedHandler) PutKeyValue(ctx context.Context, req *PutKeyValueReq, params PutKeyValueParams) (r PutKeyValueRes, _ error) {
	return r, ht.ErrNotImplemented
}

// SaveCASArtifact implements saveCASArtifact operation.
//
// Save a CAS artifact.
//
// POST /api/cache/cas/{id}
func (UnimplementedHandler) SaveCASArtifact(ctx context.Context, req SaveCASArtifactReq, params SaveCASArtifactParams) (r SaveCASArtifactRes, _ error) {
	return r, ht.ErrNotImplemented
}

// StartModuleCacheMultipartUpload implements startModuleCacheMultipartUpload operation.
//
// Start a multipart module cache upload.
//
// POST /api/cache/module/start
func (UnimplementedHandler) StartModuleCacheMultipartUpload(ctx context.Context, params StartModuleCacheMultipartUploadParams) (r StartModuleCacheMultipartUploadRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UploadModuleCachePart implements uploadModuleCachePart operation.
//
// Upload a part of a multipart module cache upload.
//
// POST /api/cache/module/part
func (UnimplementedHandler) UploadModuleCachePart(ctx context.Context, req UploadModuleCachePartReq, params UploadModuleCachePartParams) (r UploadModuleCachePartRes, _ error) {
	return r, ht.ErrNotImplemented
}
