// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CleanProjectCache implements cleanProjectCache operation.
	//
	// Clean all cache artifacts for a project.
	//
	// DELETE /api/cache/clean
	CleanProjectCache(ctx context.Context, params CleanProjectCacheParams) (CleanProjectCacheRes, error)
	// CompleteModuleCacheMultipartUpload implements completeModuleCacheMultipartUpload operation.
	//
	// Complete a multipart module cache upload.
	//
	// POST /api/cache/module/complete
	CompleteModuleCacheMultipartUpload(ctx context.Context, req *CompleteMultipartUploadRequest, params CompleteModuleCacheMultipartUploadParams) (CompleteModuleCacheMultipartUploadRes, error)
	// DownloadCASArtifact implements downloadCASArtifact operation.
	//
	// Download a CAS artifact.
	//
	// GET /api/cache/cas/{id}
	DownloadCASArtifact(ctx context.Context, params DownloadCASArtifactParams) (DownloadCASArtifactRes, error)
	// DownloadModuleCacheArtifact implements downloadModuleCacheArtifact operation.
	//
	// Download a module cache artifact.
	//
	// GET /api/cache/module/{id}
	DownloadModuleCacheArtifact(ctx context.Context, params DownloadModuleCacheArtifactParams) (DownloadModuleCacheArtifactRes, error)
	// GetKeyValue implements getKeyValue operation.
	//
	// Get a key-value entry.
	//
	// GET /api/cache/keyvalue/{cas_id}
	GetKeyValue(ctx context.Context, params GetKeyValueParams) (GetKeyValueRes, error)
	// ModuleCacheArtifactExists implements moduleCacheArtifactExists operation.
	//
	// Check if a module cache artifact exists.
	//
	// HEAD /api/cache/module/{id}
	ModuleCacheArtifactExists(ctx context.Context, params ModuleCacheArtifactExistsParams) (ModuleCacheArtifactExistsRes, error)
	// PutKeyValue implements putKeyValue operation.
	//
	// Put a key-value entry.
	//
	// PUT /api/cache/keyvalue
	PutKeyValue(ctx context.Context, req *PutKeyValueReq, params PutKeyValueParams) (PutKeyValueRes, error)
	// SaveCASArtifact implements saveCASArtifact operation.
	//
	// Save a CAS artifact.
	//
	// POST /api/cache/cas/{id}
	SaveCASArtifact(ctx context.Context, req SaveCASArtifactReq, params SaveCASArtifactParams) (SaveCASArtifactRes, error)
	// StartModuleCacheMultipartUpload implements startModuleCacheMultipartUpload operation.
	//
	// Start a multipart module cache upload.
	//
	// POST /api/cache/module/start
	StartModuleCacheMultipartUpload(ctx context.Context, params StartModuleCacheMultipartUploadParams) (StartModuleCacheMultipartUploadRes, error)
	// UploadModuleCachePart implements uploadModuleCachePart operation.
	//
	// Upload a part of a multipart module cache upload.
	//
	// POST /api/cache/module/part
	UploadModuleCachePart(ctx context.Context, req UploadModuleCachePartReq, params UploadModuleCachePartParams) (UploadModuleCachePartRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
