// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// CleanProjectCacheParams is parameters of cleanProjectCache operation.
type CleanProjectCacheParams struct {
	// The handle of the account.
	AccountHandle string
	// The handle of the project.
	ProjectHandle string
}

func unpackCleanProjectCacheParams(packed middleware.Parameters) (params CleanProjectCacheParams) {
	{
		key := middleware.ParameterKey{
			Name: "account_handle",
			In:   "query",
		}
		params.AccountHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "project_handle",
			In:   "query",
		}
		params.ProjectHandle = packed[key].(string)
	}
	return params
}

func decodeCleanProjectCacheParams(args [0]string, argsEscaped bool, r *http.Request) (params CleanProjectCacheParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: account_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "account_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "account_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProjectHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project_handle",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// CompleteModuleCacheMultipartUploadParams is parameters of completeModuleCacheMultipartUpload operation.
type CompleteModuleCacheMultipartUploadParams struct {
	// The handle of the account.
	AccountHandle string
	// The handle of the project.
	ProjectHandle string
	// The upload ID from start_multipart.
	UploadID string
}

func unpackCompleteModuleCacheMultipartUploadParams(packed middleware.Parameters) (params CompleteModuleCacheMultipartUploadParams) {
	{
		key := middleware.ParameterKey{
			Name: "account_handle",
			In:   "query",
		}
		params.AccountHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "project_handle",
			In:   "query",
		}
		params.ProjectHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "upload_id",
			In:   "query",
		}
		params.UploadID = packed[key].(string)
	}
	return params
}

func decodeCompleteModuleCacheMultipartUploadParams(args [0]string, argsEscaped bool, r *http.Request) (params CompleteModuleCacheMultipartUploadParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: account_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "account_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "account_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProjectHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: upload_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "upload_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UploadID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "upload_id",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// DownloadCASArtifactParams is parameters of downloadCASArtifact operation.
type DownloadCASArtifactParams struct {
	// The artifact identifier.
	ID string
	// The handle of the account.
	AccountHandle string
	// The handle of the project.
	ProjectHandle string
}

func unpackDownloadCASArtifactParams(packed middleware.Parameters) (params DownloadCASArtifactParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "account_handle",
			In:   "query",
		}
		params.AccountHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "project_handle",
			In:   "query",
		}
		params.ProjectHandle = packed[key].(string)
	}
	return params
}

func decodeDownloadCASArtifactParams(args [1]string, argsEscaped bool, r *http.Request) (params DownloadCASArtifactParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: account_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "account_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "account_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProjectHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project_handle",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// DownloadModuleCacheArtifactParams is parameters of downloadModuleCacheArtifact operation.
type DownloadModuleCacheArtifactParams struct {
	// The artifact identifier.
	ID string
	// The handle of the account.
	AccountHandle string
	// The handle of the project.
	ProjectHandle string
	// Artifact hash.
	Hash string
	// Artifact name.
	Name string
	// Cache category (builds).
	CacheCategory OptString `json:",omitempty,omitzero"`
}

func unpackDownloadModuleCacheArtifactParams(packed middleware.Parameters) (params DownloadModuleCacheArtifactParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "account_handle",
			In:   "query",
		}
		params.AccountHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "project_handle",
			In:   "query",
		}
		params.ProjectHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "hash",
			In:   "query",
		}
		params.Hash = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "query",
		}
		params.Name = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "cache_category",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CacheCategory = v.(OptString)
		}
	}
	return params
}

func decodeDownloadModuleCacheArtifactParams(args [1]string, argsEscaped bool, r *http.Request) (params DownloadModuleCacheArtifactParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: account_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "account_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "account_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProjectHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: hash.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "hash",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Hash = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "hash",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Name = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cache_category.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cache_category",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCacheCategoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCacheCategoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CacheCategory.SetTo(paramsDotCacheCategoryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cache_category",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetKeyValueParams is parameters of getKeyValue operation.
type GetKeyValueParams struct {
	// The CAS ID.
	CasID string
	// The handle of the account.
	AccountHandle string
	// The handle of the project.
	ProjectHandle string
}

func unpackGetKeyValueParams(packed middleware.Parameters) (params GetKeyValueParams) {
	{
		key := middleware.ParameterKey{
			Name: "cas_id",
			In:   "path",
		}
		params.CasID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "account_handle",
			In:   "query",
		}
		params.AccountHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "project_handle",
			In:   "query",
		}
		params.ProjectHandle = packed[key].(string)
	}
	return params
}

func decodeGetKeyValueParams(args [1]string, argsEscaped bool, r *http.Request) (params GetKeyValueParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: cas_id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "cas_id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.CasID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cas_id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: account_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "account_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "account_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProjectHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project_handle",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// ModuleCacheArtifactExistsParams is parameters of moduleCacheArtifactExists operation.
type ModuleCacheArtifactExistsParams struct {
	// The artifact identifier.
	ID string
	// The handle of the account.
	AccountHandle string
	// The handle of the project.
	ProjectHandle string
	// Artifact hash.
	Hash string
	// Artifact name.
	Name string
	// Cache category (builds).
	CacheCategory OptString `json:",omitempty,omitzero"`
}

func unpackModuleCacheArtifactExistsParams(packed middleware.Parameters) (params ModuleCacheArtifactExistsParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "account_handle",
			In:   "query",
		}
		params.AccountHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "project_handle",
			In:   "query",
		}
		params.ProjectHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "hash",
			In:   "query",
		}
		params.Hash = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "query",
		}
		params.Name = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "cache_category",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CacheCategory = v.(OptString)
		}
	}
	return params
}

func decodeModuleCacheArtifactExistsParams(args [1]string, argsEscaped bool, r *http.Request) (params ModuleCacheArtifactExistsParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: account_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "account_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "account_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProjectHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: hash.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "hash",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Hash = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "hash",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Name = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cache_category.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cache_category",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCacheCategoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCacheCategoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CacheCategory.SetTo(paramsDotCacheCategoryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cache_category",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// PutKeyValueParams is parameters of putKeyValue operation.
type PutKeyValueParams struct {
	// The handle of the account.
	AccountHandle string
	// The handle of the project.
	ProjectHandle string
}

func unpackPutKeyValueParams(packed middleware.Parameters) (params PutKeyValueParams) {
	{
		key := middleware.ParameterKey{
			Name: "account_handle",
			In:   "query",
		}
		params.AccountHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "project_handle",
			In:   "query",
		}
		params.ProjectHandle = packed[key].(string)
	}
	return params
}

func decodePutKeyValueParams(args [0]string, argsEscaped bool, r *http.Request) (params PutKeyValueParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: account_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "account_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "account_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProjectHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project_handle",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// SaveCASArtifactParams is parameters of saveCASArtifact operation.
type SaveCASArtifactParams struct {
	// The artifact identifier.
	ID string
	// The handle of the account.
	AccountHandle string
	// The handle of the project.
	ProjectHandle string
}

func unpackSaveCASArtifactParams(packed middleware.Parameters) (params SaveCASArtifactParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "account_handle",
			In:   "query",
		}
		params.AccountHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "project_handle",
			In:   "query",
		}
		params.ProjectHandle = packed[key].(string)
	}
	return params
}

func decodeSaveCASArtifactParams(args [1]string, argsEscaped bool, r *http.Request) (params SaveCASArtifactParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: account_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "account_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "account_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProjectHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project_handle",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// StartModuleCacheMultipartUploadParams is parameters of startModuleCacheMultipartUpload operation.
type StartModuleCacheMultipartUploadParams struct {
	// The handle of the account.
	AccountHandle string
	// The handle of the project.
	ProjectHandle string
	// Artifact hash.
	Hash string
	// Artifact name.
	Name string
	// Cache category (builds).
	CacheCategory OptString `json:",omitempty,omitzero"`
}

func unpackStartModuleCacheMultipartUploadParams(packed middleware.Parameters) (params StartModuleCacheMultipartUploadParams) {
	{
		key := middleware.ParameterKey{
			Name: "account_handle",
			In:   "query",
		}
		params.AccountHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "project_handle",
			In:   "query",
		}
		params.ProjectHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "hash",
			In:   "query",
		}
		params.Hash = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "name",
			In:   "query",
		}
		params.Name = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "cache_category",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.CacheCategory = v.(OptString)
		}
	}
	return params
}

func decodeStartModuleCacheMultipartUploadParams(args [0]string, argsEscaped bool, r *http.Request) (params StartModuleCacheMultipartUploadParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: account_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "account_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "account_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProjectHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: hash.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "hash",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Hash = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "hash",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: name.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "name",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Name = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "name",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: cache_category.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "cache_category",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotCacheCategoryVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotCacheCategoryVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.CacheCategory.SetTo(paramsDotCacheCategoryVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "cache_category",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// UploadModuleCachePartParams is parameters of uploadModuleCachePart operation.
type UploadModuleCachePartParams struct {
	// The handle of the account.
	AccountHandle string
	// The handle of the project.
	ProjectHandle string
	// The upload ID from start_multipart.
	UploadID string
	// Part number (1-indexed).
	PartNumber int
}

func unpackUploadModuleCachePartParams(packed middleware.Parameters) (params UploadModuleCachePartParams) {
	{
		key := middleware.ParameterKey{
			Name: "account_handle",
			In:   "query",
		}
		params.AccountHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "project_handle",
			In:   "query",
		}
		params.ProjectHandle = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "upload_id",
			In:   "query",
		}
		params.UploadID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "part_number",
			In:   "query",
		}
		params.PartNumber = packed[key].(int)
	}
	return params
}

func decodeUploadModuleCachePartParams(args [0]string, argsEscaped bool, r *http.Request) (params UploadModuleCachePartParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: account_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "account_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.AccountHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "account_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: project_handle.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "project_handle",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ProjectHandle = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "project_handle",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: upload_id.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "upload_id",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.UploadID = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "upload_id",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: part_number.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "part_number",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.PartNumber = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "part_number",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
