// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

const (
	AuthorizationScopes = "authorization.Scopes"
)

// CompleteMultipartUploadRequest Request to complete a multipart upload
type CompleteMultipartUploadRequest struct {
	// Parts Ordered list of part numbers that were uploaded
	Parts []int `json:"parts"`
}

// Error defines model for Error.
type Error struct {
	// Message The error message
	Message string `json:"message"`
}

// KeyValueResponse defines model for KeyValueResponse.
type KeyValueResponse struct {
	// Entries The list of key-value entries
	Entries []struct {
		// Value The value
		Value string `json:"value"`
	} `json:"entries"`
}

// StartMultipartUploadResponse Response from starting a multipart upload
type StartMultipartUploadResponse struct {
	// UploadId The upload ID to use for subsequent part uploads. Null if artifact already exists.
	UploadId *string `json:"upload_id"`
}

// DownloadCASArtifactParams defines parameters for DownloadCASArtifact.
type DownloadCASArtifactParams struct {
	// AccountHandle The handle of the account
	AccountHandle string `form:"account_handle" json:"account_handle"`

	// ProjectHandle The handle of the project
	ProjectHandle string `form:"project_handle" json:"project_handle"`
}

// SaveCASArtifactParams defines parameters for SaveCASArtifact.
type SaveCASArtifactParams struct {
	// AccountHandle The handle of the account
	AccountHandle string `form:"account_handle" json:"account_handle"`

	// ProjectHandle The handle of the project
	ProjectHandle string `form:"project_handle" json:"project_handle"`
}

// CleanProjectCacheParams defines parameters for CleanProjectCache.
type CleanProjectCacheParams struct {
	// AccountHandle The handle of the account
	AccountHandle string `form:"account_handle" json:"account_handle"`

	// ProjectHandle The handle of the project
	ProjectHandle string `form:"project_handle" json:"project_handle"`
}

// PutKeyValueJSONBody defines parameters for PutKeyValue.
type PutKeyValueJSONBody struct {
	// CasId The CAS ID
	CasId   string `json:"cas_id"`
	Entries []struct {
		// Value The value
		Value *string `json:"value,omitempty"`
	} `json:"entries"`
}

// PutKeyValueParams defines parameters for PutKeyValue.
type PutKeyValueParams struct {
	// AccountHandle The handle of the account
	AccountHandle string `form:"account_handle" json:"account_handle"`

	// ProjectHandle The handle of the project
	ProjectHandle string `form:"project_handle" json:"project_handle"`
}

// GetKeyValueParams defines parameters for GetKeyValue.
type GetKeyValueParams struct {
	// AccountHandle The handle of the account
	AccountHandle string `form:"account_handle" json:"account_handle"`

	// ProjectHandle The handle of the project
	ProjectHandle string `form:"project_handle" json:"project_handle"`
}

// CompleteModuleCacheMultipartUploadParams defines parameters for CompleteModuleCacheMultipartUpload.
type CompleteModuleCacheMultipartUploadParams struct {
	// AccountHandle The handle of the account
	AccountHandle string `form:"account_handle" json:"account_handle"`

	// ProjectHandle The handle of the project
	ProjectHandle string `form:"project_handle" json:"project_handle"`

	// UploadId The upload ID from start_multipart
	UploadId string `form:"upload_id" json:"upload_id"`
}

// UploadModuleCachePartParams defines parameters for UploadModuleCachePart.
type UploadModuleCachePartParams struct {
	// AccountHandle The handle of the account
	AccountHandle string `form:"account_handle" json:"account_handle"`

	// ProjectHandle The handle of the project
	ProjectHandle string `form:"project_handle" json:"project_handle"`

	// UploadId The upload ID from start_multipart
	UploadId string `form:"upload_id" json:"upload_id"`

	// PartNumber Part number (1-indexed)
	PartNumber int `form:"part_number" json:"part_number"`
}

// StartModuleCacheMultipartUploadParams defines parameters for StartModuleCacheMultipartUpload.
type StartModuleCacheMultipartUploadParams struct {
	// AccountHandle The handle of the account
	AccountHandle string `form:"account_handle" json:"account_handle"`

	// ProjectHandle The handle of the project
	ProjectHandle string `form:"project_handle" json:"project_handle"`

	// Hash Artifact hash
	Hash string `form:"hash" json:"hash"`

	// Name Artifact name
	Name string `form:"name" json:"name"`

	// CacheCategory Cache category (builds)
	CacheCategory *string `form:"cache_category,omitempty" json:"cache_category,omitempty"`
}

// DownloadModuleCacheArtifactParams defines parameters for DownloadModuleCacheArtifact.
type DownloadModuleCacheArtifactParams struct {
	// AccountHandle The handle of the account
	AccountHandle string `form:"account_handle" json:"account_handle"`

	// ProjectHandle The handle of the project
	ProjectHandle string `form:"project_handle" json:"project_handle"`

	// Hash Artifact hash
	Hash string `form:"hash" json:"hash"`

	// Name Artifact name
	Name string `form:"name" json:"name"`

	// CacheCategory Cache category (builds)
	CacheCategory *string `form:"cache_category,omitempty" json:"cache_category,omitempty"`
}

// ModuleCacheArtifactExistsParams defines parameters for ModuleCacheArtifactExists.
type ModuleCacheArtifactExistsParams struct {
	// AccountHandle The handle of the account
	AccountHandle string `form:"account_handle" json:"account_handle"`

	// ProjectHandle The handle of the project
	ProjectHandle string `form:"project_handle" json:"project_handle"`

	// Hash Artifact hash
	Hash string `form:"hash" json:"hash"`

	// Name Artifact name
	Name string `form:"name" json:"name"`

	// CacheCategory Cache category (builds)
	CacheCategory *string `form:"cache_category,omitempty" json:"cache_category,omitempty"`
}

// PutKeyValueJSONRequestBody defines body for PutKeyValue for application/json ContentType.
type PutKeyValueJSONRequestBody PutKeyValueJSONBody

// CompleteModuleCacheMultipartUploadJSONRequestBody defines body for CompleteModuleCacheMultipartUpload for application/json ContentType.
type CompleteModuleCacheMultipartUploadJSONRequestBody = CompleteMultipartUploadRequest
